-- SERIAL crea un contador automatico para identificar cada usuario.
CREATE TABLE "users" (
    "user_id" SERIAL PRIMARY KEY,
    "username" VARCHAR
)
-- IDENTITY es la alternativa moderna a SERIAL; DEFAULT permite indicar un ID manual si hace falta.
CREATE TABLE "users2" (
    "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR
)
-- ALWAYS genera siempre el ID automaticamente y evita valores manuales por error.
CREATE TABLE "users3" (
    "user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "username" VARCHAR
)
-- La secuencia puede configurarse: aqui inicia en 100 y suma 2 por cada fila.
CREATE TABLE "users4" (
    "user_id" INTEGER GENERATED ALWAYS AS IDENTITY
    (start with 100 INCREMENT BY 2),
    "username" VARCHAR
)

-- 

-- Una clave primaria compuesta identifica la fila con ambas columnas.
CREATE TABLE userDual(
	id1 INT,
	id2 INT,
	PRIMARY KEY(id1, id2)
)

-- 
-- UUID es un identificador unico, util cuando los datos vienen de distintos sistemas.
SELECT gen_random_uuid()
-- Habilita funciones UUID adicionales en PostgreSQL si aun no estan instaladas.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
SELECT gen_random_uuid(), uuid_generate_v1()

--

-- uuid_generate_v4() crea un UUID aleatorio como clave primaria por defecto.
CREATE TABLE users5(
	"user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	"username" VARCHAR
)

--
-- Una secuencia es un contador independiente para generar numeros unicos.
CREATE SEQUENCE user_sequence

-- Elimina la secuencia cuando ya no se necesita.
DROP SEQUENCE user_sequence

-- nextval obtiene el siguiente numero; currval muestra el ultimo de esta sesion.
SELECT nextval('user_sequence'), currval('user_sequence'), currval('user_sequence')

-- Tambien se puede usar una secuencia como valor por defecto de una columna.
CREATE TABLE users6(
	"user_id" INTEGER PRIMARY KEY default nextval('user_sequence'),
	"username" VARCHAR
)
